variables:
  PIPELINE:
    description: "Specify which pipeline to run"
    value: docs
    options: [publish, docs]

stages: [build, deploy, publish]

include:
  - component: $OUTLOUD_CI/publish-npm@4
    inputs:
      registry: [npm, gitlab]

  - component: $OUTLOUD_CI/deploy-cloudflare@4
    inputs:
      environment: production
      script:
        - |
          cd docs
          export NUXT_APP_BASE_URL=/reqo/
          pnpm install
          pnpm build --preset=cloudflare_module
          wrangler deploy --keep-vars --name=docs-reqo
      rules:
        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
          changes:
            - docs/**/*
        - if: $CI_PIPELINE_SOURCE == "web" && $PIPELINE == "docs"
