/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/museum-hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get museum hours
         * @description Get upcoming museum operating hours.
         */
        get: operations["getMuseumHours"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/special-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List special events
         * @description Return a list of upcoming special events at the museum.
         */
        get: operations["listSpecialEvents"];
        put?: never;
        /**
         * Create special events
         * @description Creates a new special event for the museum.
         */
        post: operations["createSpecialEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/special-events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get special event
         * @description Get details about a special event.
         */
        get: operations["getSpecialEvent"];
        put?: never;
        post?: never;
        /**
         * Delete special event
         * @description Delete a special event from the collection. Allows museum to cancel planned events.
         */
        delete: operations["deleteSpecialEvent"];
        options?: never;
        head?: never;
        /**
         * Update special event
         * @description Update the details of a special event.
         */
        patch: operations["updateSpecialEvent"];
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Buy museum tickets
         * @description Purchase museum tickets for general entry or special events.
         */
        post: operations["buyMuseumTickets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketId}/qr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get ticket QR code
         * @description Return an image of your ticket with scannable QR code. Used for event entry.
         */
        get: operations["getTicketCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface webhooks {
    publishNewEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * New special event added
         * @description Publish details of a new or updated event.
         */
        post: operations["publishNewEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface components {
    schemas: {
        /**
         * @description Type of ticket being purchased. Use `general` for regular museum entry and `event` for tickets to special events.
         * @example event
         * @enum {string}
         */
        TicketType: "event" | "general";
        /**
         * Format: date
         * @example 2023-10-29
         */
        Date: string;
        /**
         * Format: email
         * @description Email address for ticket purchaser.
         * @example museum-lover@example.com
         */
        Email: string;
        /** @description Data to purchase a ticket. */
        BuyMuseumTickets: {
            email?: components["schemas"]["Email"];
        } & components["schemas"]["Ticket"];
        /**
         * @description Confirmation message after a ticket purchase.
         * @example Museum general entry ticket purchased
         */
        TicketMessage: string;
        /**
         * Format: uuid
         * @description Unique identifier for museum ticket. Generated when purchased.
         * @example a54a57ca-36f8-421b-a6b4-2e8f26858a4c
         */
        TicketId: string;
        /**
         * @description Unique confirmation code used to verify ticket purchase.
         * @example ticket-event-a98c8f-7eb12
         */
        TicketConfirmation: string;
        /** @description Ticket for museum entry, can be general admission or special event. */
        Ticket: {
            ticketId?: components["schemas"]["TicketId"];
            /** @description Date when this ticket can be used for museum entry. */
            ticketDate: components["schemas"]["Date"];
            ticketType: components["schemas"]["TicketType"];
            /** @description Unique identifier for a special event. Required if purchasing tickets for the museum's special events. */
            eventId?: components["schemas"]["EventId"];
        };
        /** @description Details for a museum ticket after a successful purchase. */
        MuseumTicketsConfirmation: components["schemas"]["Ticket"] & {
            message: components["schemas"]["TicketMessage"];
            confirmationCode: components["schemas"]["TicketConfirmation"];
        };
        /**
         * Format: binary
         * @description Image of a ticket with a QR code used for museum or event entry.
         */
        TicketCodeImage: string;
        /** @description List of museum operating hours for a date range. */
        MuseumHours: components["schemas"]["MuseumDailyHours"][];
        /** @description Daily operating hours for the museum. */
        MuseumDailyHours: {
            /**
             * @description Date the operating hours apply to.
             * @example 2024-12-31
             */
            date: components["schemas"]["Date"];
            /**
             * @description Time the museum opens on a specific date. Uses 24 hour time format (`HH:mm`).
             * @example 09:00
             */
            timeOpen: string;
            /**
             * @description Time the museum closes on a specific date. Uses 24 hour time format (`HH:mm`).
             * @example 18:00
             */
            timeClose: string;
        };
        /**
         * Format: uuid
         * @description Identifier for a special event.
         * @example 3be6453c-03eb-4357-ae5a-984a0e574a54
         */
        EventId: string;
        /**
         * @description Name of the special event.
         * @example Pirate Coding Workshop
         */
        EventName: string;
        /**
         * @description Location where the special event is held.
         * @example Computer Room
         */
        EventLocation: string;
        /**
         * @description Description of the special event.
         * @example Captain Blackbeard shares his love of the C...language. And possibly Arrrrr (R lang).
         */
        EventDescription: string;
        /** @description List of planned dates for the special event. */
        EventDates: components["schemas"]["Date"][];
        /**
         * Format: float
         * @description Price of a ticket for the special event.
         * @example 25
         */
        EventPrice: number;
        SpecialEventFields: {
            name?: components["schemas"]["EventName"];
            location?: components["schemas"]["EventLocation"];
            eventDescription?: components["schemas"]["EventDescription"];
            dates?: components["schemas"]["EventDates"];
            price?: components["schemas"]["EventPrice"];
        };
        SpecialEvent: {
            eventId?: components["schemas"]["EventId"];
            name: components["schemas"]["EventName"];
            location: components["schemas"]["EventLocation"];
            eventDescription: components["schemas"]["EventDescription"];
            dates: components["schemas"]["EventDates"];
            price: components["schemas"]["EventPrice"];
        };
        /** @description List of upcoming special events. */
        SpecialEventCollection: components["schemas"]["SpecialEvent"][];
        Error: {
            /** @example object */
            type?: string;
            /** @example Validation failed */
            title?: string;
        };
    };
    responses: {
        /** @description Bad request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description Not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Page number to retrieve. */
        PaginationPage: number;
        /** @description Number of days per page. */
        PaginationLimit: number;
        /** @description Identifier for a special event. */
        EventId: string;
        /** @description Starting date to retrieve future operating hours from. Defaults to today's date. */
        StartDate: string;
        /** @description End of a date range to retrieve special events for. Defaults to 7 days after `startDate`. */
        EndDate: string;
        /** @description Identifier for a ticket to a museum event. Used to generate ticket image. */
        TicketId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMuseumHours: {
        parameters: {
            query?: {
                /** @description Starting date to retrieve future operating hours from. Defaults to today's date. */
                startDate?: components["parameters"]["StartDate"];
                /** @description Page number to retrieve. */
                page?: components["parameters"]["PaginationPage"];
                /** @description Number of days per page. */
                limit?: components["parameters"]["PaginationLimit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MuseumHours"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listSpecialEvents: {
        parameters: {
            query?: {
                /** @description Starting date to retrieve future operating hours from. Defaults to today's date. */
                startDate?: components["parameters"]["StartDate"];
                /** @description End of a date range to retrieve special events for. Defaults to 7 days after `startDate`. */
                endDate?: components["parameters"]["EndDate"];
                /** @description Page number to retrieve. */
                page?: components["parameters"]["PaginationPage"];
                /** @description Number of days per page. */
                limit?: components["parameters"]["PaginationLimit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialEventCollection"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    createSpecialEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecialEvent"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialEvent"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getSpecialEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifier for a special event. */
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialEvent"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteSpecialEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifier for a special event. */
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success - no content. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateSpecialEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifier for a special event. */
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecialEventFields"];
            };
        };
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialEvent"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    buyMuseumTickets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuyMuseumTickets"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MuseumTicketsConfirmation"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getTicketCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifier for a ticket to a museum event. Used to generate ticket image. */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scannable event ticket in image format. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": components["schemas"]["TicketCodeImage"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    publishNewEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SpecialEvent"];
            };
        };
        responses: {
            /** @description Data accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
